USE [CAMSlive]

select name, suser_sname(owner_sid) from sys.databases

CREATE USER [DESKTOP-IMKCASH\Trevor] FOR LOGIN [DESKTOP-IMKCASH\Trevor]
WITH DEFAULT_SCHEMA=[dbo]

ALTER AUTHORIZATION ON DATABASE::[CAMSlive] TO [DESKTOP-IMKCASH\Trevor]
CREATE LOGIN [DESKTOP-IMKCASH\Trevor] FROM WINDOWS;
 
ALTER DATABASE [CAMSlive] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
ALTER DATABASE [CAMSlive] SET ENABLE_BROKER; 
ALTER DATABASE [CAMSlive] SET MULTI_USER WITH ROLLBACK IMMEDIATE

ALTER DATABASE CAMSlive set TRUSTWORTHY ON; 
GO 
EXEC dbo.sp_changedbowner @loginame = N'sa', @map = false 
GO 
sp_configure 'show advanced options', 1; 
GO 
RECONFIGURE; 
GO 
sp_configure 'clr enabled', 1; 
GO 
RECONFIGURE; 
GO
 
GRANT ALTER to [DESKTOP-IMKCASH\Trevor]
GRANT CONNECT to [DESKTOP-IMKCASH\Trevor]
GRANT CONTROL to [DESKTOP-IMKCASH\Trevor]
GRANT CREATE CONTRACT to [DESKTOP-IMKCASH\Trevor]
GRANT CREATE MESSAGE TYPE to [DESKTOP-IMKCASH\Trevor]
GRANT CREATE PROCEDURE to [DESKTOP-IMKCASH\Trevor]
GRANT CREATE QUEUE to [DESKTOP-IMKCASH\Trevor]
GRANT CREATE SERVICE to [DESKTOP-IMKCASH\Trevor]
GRANT EXECUTE to [DESKTOP-IMKCASH\Trevor]
GRANT SELECT to [DESKTOP-IMKCASH\Trevor]
GRANT SUBSCRIBE QUERY NOTIFICATIONS to [DESKTOP-IMKCASH\Trevor]
GRANT VIEW DATABASE STATE to [DESKTOP-IMKCASH\Trevor]
GRANT VIEW DEFINITION to [DESKTOP-IMKCASH\Trevor]
